env:
  global:
    # SAUCE_USERNAME
    - secure: "Js6Pr7dJfvAKY5JuuuEJSrDvoBCrnjTjISMCPBmH0CkGwtGR7J2mCvaLcXQ9RO3zrSasdj8Rb6gBmrIgk1fQbp/NpwQVwMUPH4J+dhbwTHIrrIHVtxt6q8cPx43RJqjE6qN+G1MA/Y4IVbgAzjJPnzu6A6v7E/FzSFbpNilv2i4="
    # SAUCE_ACCESS_KEY
    - secure: "idJFmSy6EyMNO9UoxUx0wG83G/w8H1Sh1fG5lWodAdV01/Ft0j3KQo/zelENBx7zMWf+iqdWOhL4rBLIIkaajHbmvkMYDzhFXK4GIZmd1HnV4MZCunipscMsEbtQU+uTY/I3fersnIz74aTuj3SKlFW4jVNgvc8fawijBtTbuhU="
matrix:
  include:
  - node_js: "12"
    script:
    - npm audit
    - npm run compile
    - npm run lint
    - npm run coverage
  - node_js: "10.15"
    script:
      - npm test
  - name: "deno"
    script:
      - curl -fsSL https://deno.land/x/install/install.sh | sh
      - export PATH="$HOME/.deno/bin:$PATH"
      - deno run deno-test.ts
